version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mystore-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - '3306:3306'
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  mysql_data: {}
