import {
  LayoutDashboard,
  Users,
  UserCircle,
  Package,
  ClipboardList,
  FileText,
  Star,
  Tag,
  Megaphone,
  Settings,
  Grid,
  BarChart3,
  ShieldCheck,
} from 'lucide-react';

const links = [
  {
    to: '/admin/overview',
    key: 'overview',
    labelAr: 'نظرة عامة',
    labelEn: 'Overview',
    icon: LayoutDashboard,
    exact: true,
    quick: true,
  },
  {
    to: '/admin/orders',
    key: 'orders',
    labelAr: 'الطلبات',
    labelEn: 'Orders',
    icon: ClipboardList,
    quick: true,
  },
  {
    to: '/admin/products',
    key: 'products',
    labelAr: 'المنتجات',
    labelEn: 'Products',
    icon: Package,
    quick: true,
  },
  {
    to: '/admin/customers',
    key: 'customers',
    labelAr: 'العملاء',
    labelEn: 'Customers',
    icon: Users,
    quick: true,
  },
  {
    to: '/admin/users',
    key: 'users',
    labelAr: 'المستخدمون',
    labelEn: 'Users',
    icon: UserCircle,
    quick: true,
  },
  {
    to: '/admin/analytics',
    key: 'analytics',
    labelAr: 'التحليلات',
    labelEn: 'Analytics',
    icon: BarChart3,
    quick: true,
  },
  {
    to: '/admin/marketing',
    key: 'marketing',
    labelAr: 'التسويق',
    labelEn: 'Marketing',
    icon: Megaphone,
    quick: true,
  },
  {
    to: '/admin/brands',
    key: 'brands',
    labelAr: 'العلامات',
    labelEn: 'Brands',
    icon: Tag,
    quick: true,
  },
  {
    to: '/admin/settings',
    key: 'settings',
    labelAr: 'الإعدادات',
    labelEn: 'Settings',
    icon: Settings,
    quick: true,
  },
  {
    to: '/admin/reports',
    key: 'reports',
    labelAr: 'التقارير',
    labelEn: 'Reports',
    icon: FileText,
    quick: true,
  },
  {
    to: '/admin/reviews',
    key: 'reviews',
    labelAr: 'المراجعات',
    labelEn: 'Reviews',
    icon: Star,
    quick: true,
  },
  {
    to: '/admin/categories',
    key: 'categories',
    labelAr: 'التصنيفات',
    labelEn: 'Categories',
    icon: Grid,
  },
  {
    to: '/admin/apps',
    key: 'apps',
    labelAr: 'التطبيقات',
    labelEn: 'Apps',
    icon: Grid,
  },
  {
    to: '/admin/sellers',
    key: 'sellers',
    labelAr: 'البائعون',
    labelEn: 'Sellers',
    icon: UserCircle,
  },
  {
    to: '/admin/sellers/kyc',
    key: 'sellers_kyc',
    labelAr: 'مراجعة KYC',
    labelEn: 'KYC Review',
    icon: ShieldCheck,
  },
  {
    to: '/admin/bank-transfers',
    key: 'bank_transfers',
    labelAr: 'التحويلات البنكية',
    labelEn: 'Bank Transfers',
    icon: FileText,
  },
  {
    to: '/admin/audit',
    key: 'audit',
    labelAr: 'السجلات',
    labelEn: 'Audit Log',
    icon: FileText,
  },
  {
    to: '/admin/ads',
    key: 'ads',
    labelAr: 'الإعلانات',
    labelEn: 'Ads',
    icon: Megaphone,
    quick: true,
  },
  {
    to: '/admin/developer-settings',
    key: 'developer_settings',
    labelAr: 'إعدادات المطوّر',
    labelEn: 'Developer Settings',
    icon: Settings,
  },
];

export const adminLinks = links.map((link) => ({
  ...link,
  label: link.labelAr,
}));

export const adminQuickLinks = adminLinks.filter((link) => link.quick);

export default adminLinks;
